# Generated by Django 2.1.3 on 2018-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20181209_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='hora_venda',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
