# Generated by Django 2.1.3 on 2018-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20181209_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
