# Generated by Django 2.1.3 on 2018-12-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20181209_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='qtd_item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='valor_total_item',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
